ToolSet::CMC Class Reference
: functions for MCParticles in this class, FS -> final states, means 1 the particle will contribute to the ReconstructedParticle or 2 not decay any more (not reach the detector or not detectable
#include <CMC.h>
Static Public Member Functions
static void Set_Collider_Energy (float input)
Get_Collider_Energy : changing the collider energy, default is 500 GeV Notice: when using the CRC::InVisible(), it also will load the value from here.
static void Set_Beam_Cross_Angle (float input)
Set_Beam_Cross_Angle : changing beam crossing angle, default is 0.007 Notice: when using the CRC::InVisible(), it also will load the value from here.
static void Set_Nav_From_MC_To_RC (LCRelationNavigator *input)
Set_Nav_MC_to_RC : set default Navigator for MC to ReconstructedParticle, important for particle classification.
static float Get_Collider_Energy ()
Get_Collider_Energy : show the collider energy when generating.
static float Get_Beam_Energy ()
Get_Beam_Energy : show the energy for initial beam after having the detector simulation.
static float Get_Beam_Cross_Angle ()
Get_Beam_Cross_Angle : get the collider crossing angle.
static MCParticle * NewParticle (float px, float py, float pz, float E, MCParticle *test)
NewParticle : generate a new MCParticle Notice: this will use the `new` keyword, and generate a new MCParticle in the heap, so remember to delete this pointer.
static MCParticle * NewParticle (TLorentzVector &p, MCParticle *test)
NewParticle : generate a new MCParticle Notice: this will use the `new` keyword, and generate a new MCParticle in the heap, so remember to delete this pointer.
static MCParticle * Add (const MCParticle *MC1, const MCParticle *MC2)
Add : add four momentum of two MCParticle Notice: this will use the `new` keyword, and generate a new MCParticle in the heap, so remember to delete this pointer.
static MCParticle * Minus (const MCParticle *MC1, const MCParticle *MC2)
Minus : minus four momentum of two MCParticle Notice: this will use the `new` keyword, and generate a new MCParticle in the heap, so remember to delete this pointer.
static MCParticle * Equal (const MCParticle *MC1)
Equal : generate a new MCParticle equal to the input one This is different from use `=`, `=` will give the pointer address to the new pointer, they are still pointing to the same particle.
static TLorentzVector Minus_By_Lorentz (const MCParticle *MC1, const MCParticle *MC2)
Minus_To_Lorentz : minus four momentum of two MCParticle, return a TLorentzVector of the four momentum.
static bool Compare_as_E (const MCParticle *i, const MCParticle *j)
Compare_as_E : compare funcion by the energy for MCParticle, equals to < operator.
static bool Compare_as_Angle (const MCParticle *i, const MCParticle *j)
Compare_as_Angle : compare funcion by the costheta for MCParticle, equals to < operator.
static bool Compare_as_Pair (const std::pair< float, MCParticle * > &i, const std::pair< float, MCParticle * > &j)
Compare_as_Pair : compare function by any value paired to MCParticle*.
template<typename TMag >
static float Cal_Mag (TMag MC)
: calculate Magnitude of the four momentum
template<typename TP >
static float Cal_P (TP MC)
Cal_P : calculate the magnitude of the three momentum, |vect{P}|.
template<typename TVect >
static TVector3 Cal_Vect (TVect MC)
Cal_Vect : get three momentum.
template<typename TPT >
static float Cal_PT (TPT MC)
Cal_PT : calculate pt to the lab frame.
template<typename TPT >
static float Cal_PT (TPT MC, TPT Ref)
: calculate pt to the reference axis
template<typename TTheta >
static float Cal_CosTheta (TTheta MC)
Cal_CosTheta : calculate costheta.
template<typename TTheta >
static float Cal_CosTheta (TTheta MC, TTheta Ref)
Cal_CosTheta : calculate costheta to the reference axis.
template<typename TAngle >
static float Cal_Angle (TAngle MC, TAngle Ref)
Cal_Angle : calculate the angle of radian with acos to the reference axis.
template<typename TAngle >
static float Cal_Angle_Deg (TAngle MC, TAngle Ref)
Cal_Angle_Deg : calculate the angle of degree with acos to the reference axis.
template<typename TPhi >
static float Cal_Azimuth (TPhi MC)
Cal_Azimuth : calculate azimuth angle in the lab frame.
template<typename TPhi >
static float Cal_Azimuth (TPhi MC, TPhi Ref)
Cal_Azimuth : calculate aximuth anlge to the reference axis.
template<typename TPhi >
static float Cal_Acoplanarity (TPhi MC, TPhi Ref)
Cal_Acoplanarity : calculate acoplanarity acoplan = pi - |phi|.
static float Cal_IsolationAngle (MCParticle *MC, std::vector< MCParticle * > Ref, float minimal_energy_in_the_cone=1, float minimal_angle_from_input=2)
Cal_IsolationAngle : calculate minimal isolation angle.
static int Get_Parents_Number (MCParticle *input)
functions for get basic particle properties
static int Get_Daughters_Number (MCParticle *input)
Get_Daughters_Number : daughter number.
static std::vector< int > Get_ParentsPID (MCParticle *MC)
Get_ParentsPID : parents PDG code.
static std::vector< int > Get_DaughtersPID (MCParticle *MC)
Get_DaughtersPID : daughter's PDG code.
static bool Status_Beam_Energy (MCParticle *input)
Status_Beam_Energy : whether the input energy equals to the beam energy.
static bool Status_Has_Parent (MCParticle *input)
Status_Has_Parent : whether has the parents Notice: for current ILD event generation, if no parents -> initial beam have parents, but no grand parents -> beam after ISR and ISR photons have grand parents, no parents of grand parents -> hard scattering particle generated in the Whizard.
static bool Status_Has_GrandParent (MCParticle *input)
Status_Has_GrandParent : whether has the grand parents.
static bool Status_Has_Daughter (MCParticle *input)
Status_Has_Daughter : whether has the daughter.
static bool Status_Has_GrandDaughter (MCParticle *input)
Status_Has_GrandDaughter : whether has the grand daughter.
static bool Status_Is_MS (MCParticle *input)
Status_Is_MS : whether is a intermediate particle, (generator status==2).
static bool Status_Is_TFS (MCParticle *input)
Status_Is_TFS : whether is a final state, (Pythia final states or simulation final states).
static bool Status_Is_Pythia_TFS (MCParticle *input)
Status_Is_Pythia_TFS :whether is a Pythia stable particle.
static bool Status_Is_Detector_TFS (MCParticle *input)
Status_Is_Detector_TFS : whether is a possible detector simulated final state.
static bool Status_Is_Pythia (MCParticle *input)
Status_Is_Pythia : whether a possible final state generated from Pythia.
static bool Status_Is_Overlay (MCParticle *input)
Status_Is_Overlay : Whether generated from Overlay.
static bool Status_Is_Overlay_DFS (MCParticle *input)
Status_Is_Overlay_DFS : whether a possible Overlay final states.
static bool Status_Is_Stopped (MCParticle *input)
static bool Status_Is_DecayInTracker (MCParticle *input)
static bool Status_Is_DecayInCalorimeter (MCParticle *input)
static bool Status_Is_LeftDetector (MCParticle *input)
static bool Status_Is_Electron (MCParticle *input)
static bool Status_Is_Muon (MCParticle *input)
static bool Status_Is_Tau (MCParticle *input)
static bool Status_Is_Lepton (MCParticle *input)
static bool Status_Is_Neutrino (MCParticle *input)
static bool Status_Is_HeavyBoson (MCParticle *input)
static bool Status_Is_Photon (MCParticle *input)
static bool Status_Is_NeutralHadron (MCParticle *input)
static bool Status_Is_ChargedHadron (MCParticle *input)
static bool Status_Is_Gluon (MCParticle *input)
static bool Status_Is_Quark (MCParticle *input)
static bool Status_Is_LightQuark (MCParticle *input)
static bool Status_Is_HeavyQuark (MCParticle *input)
static bool Status_Is_TopQuark (MCParticle *input)
static bool Status_Is_BottomQuark (MCParticle *input)
static bool Status_Is_CharmQuark (MCParticle *input)
static bool Judge_Is_Beam (MCParticle *input)
Judge_Is_Beam : whether it is the beam initial electron/positron.
static bool Judge_Parents_Are_Beam (MCParticle *input)
Judge_Parents_Are_Beam : whether its parents are initial beam (i.e.
static bool Judge_GrandParents_Are_Beam (MCParticle *input)
Judge_GrandParents_Are_Beam : whether its grand parents are initial beam (i.e.
static bool Judge_Is_IS_Electron (MCParticle *input)
Judge_Is_IS_Electron : is the electron/positron after the ISR.
static bool Judge_Is_IS_Photon (MCParticle *input)
Judge_Is_IS_Photon : is the ISR photon.
static bool Judge_HardScattering_FS (MCParticle *input)
Judge_HardScattering_FS : is the hard-scattering states (including ISR photon).
static bool Judge_HardScattering_Next_FS (MCParticle *input)
Judge_HardScattering_Next_FS : is the first level decay of the hard-scattering states.
static bool Judge_HardScattering_Next_Next_FS (MCParticle *input)
Judge_HardScattering_Next_Next_FS : is the second level decay of the hard-scattering states.
static bool Judge_OnlyPythiaShowering_FS (MCParticle *input, LCRelationNavigator *&relation=_nav_MC_to_RC)
Judge_OnlyPythiaShowering_FS : is the pythia stable final states, but directly contribute to ReconstructedParticle.
static bool Judge_PythiaShowering_FS (MCParticle *input)
Judge_PythiaShowering_FS : is the pythia statble final states.
static bool Judge_PythiaShowering_All (MCParticle *input)
Judge_PythiaShowering_All : is generated by Pythia.
static bool Judge_OnlyDetectorSimulating_FS (MCParticle *input, LCRelationNavigator *&relation=_nav_MC_to_RC)
Judge_OnlyDetectorSimulating_FS : is generated in simulation and don't have daughter.
static bool Judge_DetectorSimulating_FS (MCParticle *input)
Judge_DetectorSimulating_FS : is the final states which will contribute to the ReconstructedParticle, not including the overlay.
static bool Judge_Overlay_FS (MCParticle *input, LCRelationNavigator *&relation=_nav_MC_to_RC)
Judge_Overlay_FS : is overlay and don't have daughter.
static bool Judge_Has_Overlay (std::vector< MCParticle * > input)
Judge_Has_Overlay : has overlay particle in this vector.
static bool Judge_All_FS (MCParticle *input, LCRelationNavigator *&relation=_nav_MC_to_RC)
Judge_All_FS : all the final states which will contribute to the ReconstructedParticle, including the overlay.
static std::vector< MCParticle * > Get_Particle (bool(*Judge)(MCParticle *), std::vector< MCParticle * > AllMC)
Get_Particle : get a special kind of MCParticle, depending on the input function.
static std::vector< MCParticle * > Get_MCParticle (LCCollection *AllMC)
Get_MCParticle : get all MCParticles into a vector from the LCCollection MCParticle.
static std::vector< MCParticle * > Get_MC_HardScattering_FS (std::vector< MCParticle * > MCs)
Get_MC_HardScattering_FS.
static std::vector< MCParticle * > Get_MC_PythiaShowering_FS (std::vector< MCParticle * > MCs)
static std::vector< MCParticle * > Get_MC_OnlyPythiaShowering_FS (std::vector< MCParticle * > MCs)
static std::vector< MCParticle * > Get_MC_DetectorSimulating_FS (std::vector< MCParticle * > MCs)
static std::vector< MCParticle * > Get_MC_OnlyDetectorSimulating_FS (std::vector< MCParticle * > MCs)
static std::vector< MCParticle * > Get_MC_Overlay_FS (std::vector< MCParticle * > MCs)
static std::vector< MCParticle * > Get_MC_All_FS (std::vector< MCParticle * > MCs)
static std::vector< MCParticle * > Get_MC_PythiaShowering_All (std::vector< MCParticle * > MCs)
static std::vector< MCParticle * > Get_MC_DetectorSimulating_All (std::vector< MCParticle * > MCs)
static std::vector< MCParticle * > Get_MC_Overlay_All (std::vector< MCParticle * > MCs)
static std::vector< MCParticle * > MCToPythiaShowering (MCParticle *input)
static std::vector< MCParticle * > MCToHardScattering (MCParticle *input)
static void Get_MC_HardScattering_Sort (std::vector< MCParticle * > MCs, std::vector< MCParticle * > &ISRlepton, std::vector< MCParticle * > &ISRphoton, std::vector< MCParticle * > &ObjetctParticle)
static std::vector< MCParticle * > Get_MCParticleType (std::vector< MCParticle * > MCs, signed int PDG)
static std::vector< MCParticle * > Get_MCParticleType_Abs (std::vector< MCParticle * > MCs, signed int PDG)
static std::vector< MCParticle * > Get_MCParticleType (std::vector< MCParticle * > MCs, std::string PDG)
static float Get_DecayChannel (MCParticle *input)
static void Remove_Duplication (std::vector< MCParticle * > &MCs)
static std::vector< MCParticle * > Pass_DetectorAngle (std::vector< MCParticle * > &MCs)
static MCParticle * Get_Visible (std::vector< MCParticle * > in)
static MCParticle * Get_InVisible (std::vector< MCParticle * > in)
static TLorentzVector Get_Visible_To_Lorentz (std::vector< MCParticle * > in)
static TLorentzVector Get_InVisible_To_Lorentz (std::vector< MCParticle * > in)
static std::vector< MCParticle * > Get_Isolated (std::vector< MCParticle * > input, std::vector< MCParticle * > all, std::vector< MCParticle * > left)
static bool IsInCone (MCParticle *lep, MCParticle *pfo, float angle_cut)
Detailed Description
: functions for MCParticles in this class, FS -> final states, means 1 the particle will contribute to the ReconstructedParticle or 2 not decay any more (not reach the detector or not detectable PythiaShowering -> the parton shower generated by the pythia (or maybe other generator e.g. Herwig.) DetectorSimulating -> the particle generated in the detector simulation
Member Function Documentation
static MCParticle* ToolSet::CMC::Add (const MCParticle * MC1, const MCParticle * MC2) [static]
Add : add four momentum of two MCParticle Notice: this will use the `new` keyword, and generate a new MCParticle in the heap, so remember to delete this pointer.
Parameters
MC1
MC2
Returns
template<typename TPhi > static float ToolSet::CMC::Cal_Acoplanarity (TPhi MC, TPhi Ref) [inline, static]
Cal_Acoplanarity : calculate acoplanarity acoplan = pi - |phi|.
Template Parameters
TPhi
Parameters
MC
Ref
Returns
template<typename TAngle > static float ToolSet::CMC::Cal_Angle (TAngle MC, TAngle Ref) [inline, static]
Cal_Angle : calculate the angle of radian with acos to the reference axis.
Template Parameters
TAngle
Parameters
MC
Ref
Returns
template<typename TAngle > static float ToolSet::CMC::Cal_Angle_Deg (TAngle MC, TAngle Ref) [inline, static]
Cal_Angle_Deg : calculate the angle of degree with acos to the reference axis.
Template Parameters
TAngle
Parameters
MC
Ref
Returns
Referenced by Cal_IsolationAngle().
template<typename TPhi > static float ToolSet::CMC::Cal_Azimuth (TPhi MC, TPhi Ref) [inline, static]
Cal_Azimuth : calculate aximuth anlge to the reference axis.
Template Parameters
TPhi
Parameters
MC
Ref
Returns
template<typename TPhi > static float ToolSet::CMC::Cal_Azimuth (TPhi MC) [inline, static]
Cal_Azimuth : calculate azimuth angle in the lab frame.
Template Parameters
TPhi
Parameters
MC
Returns
template<typename TTheta > static float ToolSet::CMC::Cal_CosTheta (TTheta MC, TTheta Ref) [inline, static]
Cal_CosTheta : calculate costheta to the reference axis.
Template Parameters
TTheta
Parameters
MC
Ref
Returns
template<typename TTheta > static float ToolSet::CMC::Cal_CosTheta (TTheta MC) [inline, static]
Cal_CosTheta : calculate costheta.
Template Parameters
TTheta
Parameters
MC
Returns
Referenced by Compare_as_Angle().
static float ToolSet::CMC::Cal_IsolationAngle (MCParticle * MC, std::vector< MCParticle * > Ref, float minimal_energy_in_the_cone = 1, float minimal_angle_from_input = 2) [inline, static]
Cal_IsolationAngle : calculate minimal isolation angle.
Parameters
MC
Ref
Returns
References Cal_Angle_Deg(), and Compare_as_Pair().
template<typename TMag > static float ToolSet::CMC::Cal_Mag (TMag MC) [inline, static]
: calculate Magnitude of the four momentum
Template Parameters
TMag
Parameters
MC
Returns
template<typename TP > static float ToolSet::CMC::Cal_P (TP MC) [inline, static]
Cal_P : calculate the magnitude of the three momentum, |vect{P}|.
Template Parameters
TP
Parameters
MC
Returns
template<typename TPT > static float ToolSet::CMC::Cal_PT (TPT MC, TPT Ref) [inline, static]
: calculate pt to the reference axis
Template Parameters
TPT
Parameters
@param
Returns
template<typename TPT > static float ToolSet::CMC::Cal_PT (TPT MC) [inline, static]
Cal_PT : calculate pt to the lab frame.
Template Parameters
TPT
Parameters
MC
Returns
template<typename TVect > static TVector3 ToolSet::CMC::Cal_Vect (TVect MC) [inline, static]
Cal_Vect : get three momentum.
Template Parameters
TVect
Parameters
MC
Returns
static bool ToolSet::CMC::Compare_as_Angle (const MCParticle * i, const MCParticle * j) [inline, static]
Compare_as_Angle : compare funcion by the costheta for MCParticle, equals to < operator.
Parameters
i
j
Returns
References Cal_CosTheta().
static bool ToolSet::CMC::Compare_as_E (const MCParticle * i, const MCParticle * j) [inline, static]
Compare_as_E : compare funcion by the energy for MCParticle, equals to < operator.
Parameters
i
j
Returns
static bool ToolSet::CMC::Compare_as_Pair (const std::pair< float, MCParticle * > & i, const std::pair< float, MCParticle * > & j) [inline, static]
Compare_as_Pair : compare function by any value paired to MCParticle*.
Parameters
i
j
Returns
Referenced by Cal_IsolationAngle().
static MCParticle* ToolSet::CMC::Equal (const MCParticle * MC1) [static]
Equal : generate a new MCParticle equal to the input one This is different from use `=`, `=` will give the pointer address to the new pointer, they are still pointing to the same particle. But `equal` will generate a new MCParticle, whose property is the same with the old one. Notice: this will use the `new` keyword, and generate a new MCParticle in the heap, so remember to delete this pointer
Parameters
MC1
Returns
static float ToolSet::CMC::Get_Beam_Cross_Angle () [static]
Get_Beam_Cross_Angle : get the collider crossing angle.
Returns
static float ToolSet::CMC::Get_Beam_Energy () [static]
Get_Beam_Energy : show the energy for initial beam after having the detector simulation. Notice: for ILC, there will be a x-direction boost, so the beam energy is not collider_energy/2 any more, but a little larger.
Returns
static float ToolSet::CMC::Get_Collider_Energy () [static]
Get_Collider_Energy : show the collider energy when generating.
Returns
static int ToolSet::CMC::Get_Daughters_Number (MCParticle * input) [static]
Get_Daughters_Number : daughter number.
Parameters
input
Returns
static std::vector<int> ToolSet::CMC::Get_DaughtersPID (MCParticle * MC) [static]
Get_DaughtersPID : daughter's PDG code.
Parameters
MC
Returns
static std::vector<MCParticle*> ToolSet::CMC::Get_MC_HardScattering_FS (std::vector< MCParticle * > MCs) [static]
Get_MC_HardScattering_FS.
Parameters
MCs
Returns
static std::vector<MCParticle*> ToolSet::CMC::Get_MCParticle (LCCollection * AllMC) [static]
Get_MCParticle : get all MCParticles into a vector from the LCCollection MCParticle.
Parameters
AllMC
Returns
static int ToolSet::CMC::Get_Parents_Number (MCParticle * input) [static]
functions for get basic particle properties Get_Parents_Number : parents number
Parameters
input
Returns
static std::vector<int> ToolSet::CMC::Get_ParentsPID (MCParticle * MC) [static]
Get_ParentsPID : parents PDG code.
Parameters
MC
Returns
static std::vector<MCParticle*> ToolSet::CMC::Get_Particle (bool(*)(MCParticle *) Judge, std::vector< MCParticle * > AllMC) [static]
Get_Particle : get a special kind of MCParticle, depending on the input function.
Remarks
functions for get special particle vector
Parameters
Judge : a judge function that provided before, in order to use all functions, you have to set default Navigator first.
AllMC : a vector of MCParticle*
Returns
static bool ToolSet::CMC::Judge_All_FS (MCParticle * input, LCRelationNavigator *& relation = _nav_MC_to_RC) [static]
Judge_All_FS : all the final states which will contribute to the ReconstructedParticle, including the overlay.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_DetectorSimulating_FS (MCParticle * input) [static]
Judge_DetectorSimulating_FS : is the final states which will contribute to the ReconstructedParticle, not including the overlay.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_GrandParents_Are_Beam (MCParticle * input) [static]
Judge_GrandParents_Are_Beam : whether its grand parents are initial beam (i.e. input is the hard-scattering states)
Parameters
input
Returns
static bool ToolSet::CMC::Judge_HardScattering_FS (MCParticle * input) [static]
Judge_HardScattering_FS : is the hard-scattering states (including ISR photon).
Parameters
input
Returns
static bool ToolSet::CMC::Judge_HardScattering_Next_FS (MCParticle * input) [static]
Judge_HardScattering_Next_FS : is the first level decay of the hard-scattering states.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_HardScattering_Next_Next_FS (MCParticle * input) [static]
Judge_HardScattering_Next_Next_FS : is the second level decay of the hard-scattering states.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_Has_Overlay (std::vector< MCParticle * > input) [static]
Judge_Has_Overlay : has overlay particle in this vector.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_Is_Beam (MCParticle * input) [static]
Judge_Is_Beam : whether it is the beam initial electron/positron.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_Is_IS_Electron (MCParticle * input) [static]
Judge_Is_IS_Electron : is the electron/positron after the ISR.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_Is_IS_Photon (MCParticle * input) [static]
Judge_Is_IS_Photon : is the ISR photon.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_OnlyDetectorSimulating_FS (MCParticle * input, LCRelationNavigator *& relation = _nav_MC_to_RC) [static]
Judge_OnlyDetectorSimulating_FS : is generated in simulation and don't have daughter.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_OnlyPythiaShowering_FS (MCParticle * input, LCRelationNavigator *& relation = _nav_MC_to_RC) [static]
Judge_OnlyPythiaShowering_FS : is the pythia stable final states, but directly contribute to ReconstructedParticle.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_Overlay_FS (MCParticle * input, LCRelationNavigator *& relation = _nav_MC_to_RC) [static]
Judge_Overlay_FS : is overlay and don't have daughter.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_Parents_Are_Beam (MCParticle * input) [static]
Judge_Parents_Are_Beam : whether its parents are initial beam (i.e. the input is the ISR or the beam after ISR)
Parameters
input
Returns
static bool ToolSet::CMC::Judge_PythiaShowering_All (MCParticle * input) [static]
Judge_PythiaShowering_All : is generated by Pythia.
Parameters
input
Returns
static bool ToolSet::CMC::Judge_PythiaShowering_FS (MCParticle * input) [static]
Judge_PythiaShowering_FS : is the pythia statble final states.
Parameters
input
Returns
static MCParticle* ToolSet::CMC::Minus (const MCParticle * MC1, const MCParticle * MC2) [static]
Minus : minus four momentum of two MCParticle Notice: this will use the `new` keyword, and generate a new MCParticle in the heap, so remember to delete this pointer.
Parameters
MC1
MC2
Returns
static TLorentzVector ToolSet::CMC::Minus_By_Lorentz (const MCParticle * MC1, const MCParticle * MC2) [static]
Minus_To_Lorentz : minus four momentum of two MCParticle, return a TLorentzVector of the four momentum.
Parameters
MC1
MC2
Returns
static MCParticle* ToolSet::CMC::NewParticle (TLorentzVector & p, MCParticle * test) [static]
NewParticle : generate a new MCParticle Notice: this will use the `new` keyword, and generate a new MCParticle in the heap, so remember to delete this pointer.
Parameters
p
test : this is only for function overload, it doesn't have really usage, so you can provide any MCParticle* type pointer
Returns
static MCParticle* ToolSet::CMC::NewParticle (float px, float py, float pz, float E, MCParticle * test) [static]
NewParticle : generate a new MCParticle Notice: this will use the `new` keyword, and generate a new MCParticle in the heap, so remember to delete this pointer.
Parameters
px
py
pz
E
test : this is only for function overload, it doesn't have really usage, so you can provide any MCParticle* type pointer
Returns
static void ToolSet::CMC::Set_Beam_Cross_Angle (float input) [static]
Set_Beam_Cross_Angle : changing beam crossing angle, default is 0.007 Notice: when using the CRC::InVisible(), it also will load the value from here.
Parameters
input
static void ToolSet::CMC::Set_Collider_Energy (float input) [static]
Get_Collider_Energy : changing the collider energy, default is 500 GeV Notice: when using the CRC::InVisible(), it also will load the value from here.
Returns
static void ToolSet::CMC::Set_Nav_From_MC_To_RC (LCRelationNavigator * input) [static]
Set_Nav_MC_to_RC : set default Navigator for MC to ReconstructedParticle, important for particle classification.
Parameters
input
static bool ToolSet::CMC::Status_Beam_Energy (MCParticle * input) [static]
Status_Beam_Energy : whether the input energy equals to the beam energy.
Parameters
input
Returns
static bool ToolSet::CMC::Status_Has_Daughter (MCParticle * input) [static]
Status_Has_Daughter : whether has the daughter.
Parameters
input
Returns
static bool ToolSet::CMC::Status_Has_GrandDaughter (MCParticle * input) [static]
Status_Has_GrandDaughter : whether has the grand daughter.
Parameters
input
Returns
static bool ToolSet::CMC::Status_Has_GrandParent (MCParticle * input) [static]
Status_Has_GrandParent : whether has the grand parents.
Parameters
input
Returns
static bool ToolSet::CMC::Status_Has_Parent (MCParticle * input) [static]
Status_Has_Parent : whether has the parents Notice: for current ILD event generation, if no parents -> initial beam have parents, but no grand parents -> beam after ISR and ISR photons have grand parents, no parents of grand parents -> hard scattering particle generated in the Whizard.
Parameters
input
Returns
static bool ToolSet::CMC::Status_Is_Detector_TFS (MCParticle * input) [static]
Status_Is_Detector_TFS : whether is a possible detector simulated final state.
Parameters
input
Returns
static bool ToolSet::CMC::Status_Is_MS (MCParticle * input) [static]
Status_Is_MS : whether is a intermediate particle, (generator status==2).
Parameters
input
Returns
static bool ToolSet::CMC::Status_Is_Overlay (MCParticle * input) [static]
Status_Is_Overlay : Whether generated from Overlay.
Parameters
input
Returns
static bool ToolSet::CMC::Status_Is_Overlay_DFS (MCParticle * input) [static]
Status_Is_Overlay_DFS : whether a possible Overlay final states.
Parameters
input
Returns
static bool ToolSet::CMC::Status_Is_Pythia (MCParticle * input) [static]
Status_Is_Pythia : whether a possible final state generated from Pythia.
Parameters
input
Returns
static bool ToolSet::CMC::Status_Is_Pythia_TFS (MCParticle * input) [static]
Status_Is_Pythia_TFS :whether is a Pythia stable particle.
Parameters
input
Returns
static bool ToolSet::CMC::Status_Is_TFS (MCParticle * input) [static]
Status_Is_TFS : whether is a final state, (Pythia final states or simulation final states).
Parameters
input
Returns
The documentation for this class was generated from the following file:
CMC.h