ToolSet::CChain_Single Class Reference
: Getting the decay chain It contains two part: MC and Reconstructed part in this class.
#include <CChain_Single.h>
Public Member Functions
CChain_Single ()
CChain_Single : normal constructor.
CChain_Single (MCParticle *input)
CChain_Single : constructor, directly build the chain of the MC part.
CChain_Single (ReconstructedParticle *input)
CChain_Single : constructor, build the chain of the ReconstructedParticle part.
MCParticle * Input ()
Input : get all input MC particles.
ReconstructedParticle * Input_RC ()
Input_RC : get all input RC particles.
std::vector< MCParticle * > Head ()
Head : get the hard-scattering particles for the chain.
std::vector< MCParticle * > Next_Head ()
Next_Head : get first decay products from the hard-scattering particles in the chains.
std::vector< MCParticle * > Next_Next_Head ()
Next_Next_Head : get first decay products from the hard-scattering particles in the chains.
std::vector< MCParticle * > Chain ()
Chain: get all MC particles in each chains (from hard-scattering to final simulated particle, has duplicated ones).
std::vector< MCParticle * > Trim_Chain ()
Trim_Chain : get trimed MC particles in the chain (from hard-scattering to final simulated particle).
Chain_Type End ()
End : get all final states including MCParticles and the corresponding ReconstructedParticle (as well as their weights) in the chain.
std::vector< MCParticle * > MCEnd ()
MCEnd : get final states in the MC part in the chain.
std::vector< Chain_End_Type > RC ()
RC : get ReconstructedParticle in the chain, it organizes as for each particle in the MCEnd, it has a MCparticle---vector of <(weight, ReconstructedParticle)>.
std::vector< std::vector< ReconstructedParticle * > > RC_Particle ()
RC_Particle : get ReconstructedParticle in the chain， it organizes as for each particle in the MCEnd, it has a MCParticle -- vector of <ReconstructedParticles>.
std::vector< std::vector< float > > RC_Weight ()
RC_Weight : get ReconstructedParticle's weight in the chain， it organizes as for each particle in the MCEnd, it has a MCParticle -- vector of <weight>.
std::vector< ReconstructedParticle * > Flat_RC ()
Flat_RC : get all posible ReconstructedParticle in the chain, comparing Get_RC(), it removes duplicated ones.
ReconstructedParticle * Combined_RC ()
Combined_RC : sum all ReconstructedParticle into a new particle in the chain, so that you can compare the energy/momentum loss between original MC particle and ReconstructedParticles.
std::vector< MCParticle * > FromRC_MC ()
FromRC_MC : get MCParticles from ReconstructedParticles with other direction linker in the chain.
std::vector< float > FromRC_Weight ()
FromRC_Weight : get MCParticles weight from ReconstructedParticles with other direction linker in the chain.
std::vector< MCParticle * > Extra_MC ()
Extra_MC : show the extra contributions for the ReconstructedParticle from other particles that not in the chain.
LCRelationNavigator * Nav_From_MC_to_RC ()
Nav_From_MC_to_RC : Nav, input is MC, return the related ReconstructedParticle.
LCRelationNavigator * Nav_from_RC_to_MC ()
Nav_from_RC_to_MC : Nav, input is ReconstructedParticle, return the related MCParticle.
bool Has_Trim_Chain ()
Has_Trim_Chain : return flag for trim duplicated particles in the chain.
bool Has_Set_RC ()
Has_Set_RC : return flag for set Reconstructed part.
bool Has_Set_MC ()
Has_Set_MC : return flag for set MC part.
void Init ()
void Print ()
void Clear ()
Clear : Notice: Remember to Clear the chain after use it.
void Set_Nav_From_MC_To_RC (LCRelationNavigator *relation)
Set_Nav_From_MC_To_RC : set Nav.
void Set_Nav_From_RC_To_MC (LCRelationNavigator *relation)
Set_Nav_From_RC_To_MC : set Nav.
void Set_RC ()
Set_RC : if having the MC part, with this command, it can first get all corresponding ReconstructedParticles from the final states in the MC parts, then set all RC part structure, it also includes Set_End_Type(), Set_Flat_RC(), Set_MC_From_Flat_RC(), Set_Extra_MC(), Set_Combined_RC().
void Set_Flat_RC ()
Set_Flat_RC : get all posible ReconstructedParticle , it collects all ReconstructedParticles in the chain and removes duplicated ones.
void Set_Combined_RC ()
Set_Combined_RC : sum all ReconstructedParticle into a new particle in each chains, so that you can compare the energy/momentum loss between original MC particle and ReconstructedParticles.
void Set_MC_From_Flat_RC ()
Set_MC_From_Flat_RC : after having ReconstructedParticles, using this to get corresponding MCParticles.
void Set_Extra_MC ()
Set_Extra_MC : set the extra contributions for the ReconstructedParticle from other particles that not in this chain.
void Set_Trim_Chain ()
Set_Trim_Chain : trim duplicated particles in the decay chain, this is more useful in the Hadron Collider.
void Minimize_Trim_Chain ()
Minimize_Trim_Chain : minimize the trim chain.
void Set_MC_End ()
Set_MC_End : remove duplicated MC final states ().
void Set_End_Type ()
Set_End_Type : build relation between MC final states and ReconstructedParticles.
void Set_MC ()
Set_MC : using ReconstructedParticle to set MCParticle part.
void Build_Chain (MCParticle *input)
Build_Chain : build MC parts structure.
void Recurse_Chain (MCParticle *input)
Recurse_Chain : get decay particles from the input.
void Push_Back (MCParticle *input)
Push_Back : recurse function in the Recurse_Chain().
void TraceBack_Chain (MCParticle *input)
TraceBack_Chain : get particles where the input is decayed from, it is in the opposite direction of the Recurse_Chain().
void Push_Forward (MCParticle *input)
Push_Forward : recurse function in the TraceBack_Chain().
void Build_Chain_FromRCFS (ReconstructedParticle *input)
Build_Chain_FromRCFS : bulid Reconstructed part structure.
Detailed Description
: Getting the decay chain It contains two part: MC and Reconstructed part in this class. for MCParticle, its stucture is head->decay products -> ... -> many pythia final states -> ... -> many detector simulation final states. then all final states will get their corresponding ReconstructedParticles with the MCTruthRecoLink these MCParticle final states as well as their corresponding ReconstructedParticles and weights are stored as pairs together in the Chain_Type Finally, the ReconstructedParticles also can find their corresponding MCParticles, these MCParticles can be different from the original MC final states, because some ReconstructedParticles have the contribution from other source.
Constructor & Destructor Documentation
ToolSet::CChain_Single::CChain_Single (MCParticle * input) [inline]
CChain_Single : constructor, directly build the chain of the MC part.
Parameters
input
References Build_Chain().
ToolSet::CChain_Single::CChain_Single (ReconstructedParticle * input) [inline]
CChain_Single : constructor, build the chain of the ReconstructedParticle part.
Parameters
input
References Build_Chain_FromRCFS().
Member Function Documentation
void ToolSet::CChain_Single::Build_Chain (MCParticle * input)
Build_Chain : build MC parts structure.
Parameters
input
Referenced by CChain_Single().
void ToolSet::CChain_Single::Build_Chain_FromRCFS (ReconstructedParticle * input)
Build_Chain_FromRCFS : bulid Reconstructed part structure.
Parameters
input
Referenced by CChain_Single().
std::vector<MCParticle*> ToolSet::CChain_Single::Chain () [inline]
Chain: get all MC particles in each chains (from hard-scattering to final simulated particle, has duplicated ones).
Returns
void ToolSet::CChain_Single::Clear ()
Clear : Notice: Remember to Clear the chain after use it. If you use combined_RC command, it will build a `new` Particle. So you need to delete this point with Clear() function. I didn't write Clear() into deconstructor because it may cause some trouble when transfer the chain to other functions.
ReconstructedParticle* ToolSet::CChain_Single::Combined_RC () [inline]
Combined_RC : sum all ReconstructedParticle into a new particle in the chain, so that you can compare the energy/momentum loss between original MC particle and ReconstructedParticles. This will generate a new ReconstructedParticle in the heap, so remember to use Clear() function after using CChain_Vec
Returns
Chain_Type ToolSet::CChain_Single::End () [inline]
End : get all final states including MCParticles and the corresponding ReconstructedParticle (as well as their weights) in the chain.
Returns
std::vector<MCParticle*> ToolSet::CChain_Single::Extra_MC () [inline]
Extra_MC : show the extra contributions for the ReconstructedParticle from other particles that not in the chain.
Returns
std::vector<ReconstructedParticle*> ToolSet::CChain_Single::Flat_RC () [inline]
Flat_RC : get all posible ReconstructedParticle in the chain, comparing Get_RC(), it removes duplicated ones.
Returns
std::vector<MCParticle*> ToolSet::CChain_Single::FromRC_MC () [inline]
FromRC_MC : get MCParticles from ReconstructedParticles with other direction linker in the chain. It's important for cross check particle reconstruction.
Returns
std::vector<float> ToolSet::CChain_Single::FromRC_Weight () [inline]
FromRC_Weight : get MCParticles weight from ReconstructedParticles with other direction linker in the chain. It's important for cross check particle reconstruction.
Returns
bool ToolSet::CChain_Single::Has_Set_MC () [inline]
Has_Set_MC : return flag for set MC part.
Returns
bool ToolSet::CChain_Single::Has_Set_RC () [inline]
Has_Set_RC : return flag for set Reconstructed part.
Returns
bool ToolSet::CChain_Single::Has_Trim_Chain () [inline]
Has_Trim_Chain : return flag for trim duplicated particles in the chain.
Returns
std::vector<MCParticle*> ToolSet::CChain_Single::Head () [inline]
Head : get the hard-scattering particles for the chain.
Returns
MCParticle* ToolSet::CChain_Single::Input () [inline]
Input : get all input MC particles.
Returns
ReconstructedParticle* ToolSet::CChain_Single::Input_RC () [inline]
Input_RC : get all input RC particles.
Returns
std::vector<MCParticle*> ToolSet::CChain_Single::MCEnd () [inline]
MCEnd : get final states in the MC part in the chain.
Returns
LCRelationNavigator* ToolSet::CChain_Single::Nav_From_MC_to_RC () [inline]
Nav_From_MC_to_RC : Nav, input is MC, return the related ReconstructedParticle.
Returns
LCRelationNavigator* ToolSet::CChain_Single::Nav_from_RC_to_MC () [inline]
Nav_from_RC_to_MC : Nav, input is ReconstructedParticle, return the related MCParticle.
Returns
std::vector<MCParticle*> ToolSet::CChain_Single::Next_Head () [inline]
Next_Head : get first decay products from the hard-scattering particles in the chains.
Returns
std::vector<MCParticle*> ToolSet::CChain_Single::Next_Next_Head () [inline]
Next_Next_Head : get first decay products from the hard-scattering particles in the chains.
Returns
void ToolSet::CChain_Single::Push_Back (MCParticle * input)
Push_Back : recurse function in the Recurse_Chain().
Parameters
input
void ToolSet::CChain_Single::Push_Forward (MCParticle * input)
Push_Forward : recurse function in the TraceBack_Chain().
Parameters
input
std::vector<Chain_End_Type> ToolSet::CChain_Single::RC () [inline]
RC : get ReconstructedParticle in the chain, it organizes as for each particle in the MCEnd, it has a MCparticle---vector of <(weight, ReconstructedParticle)>.
Returns
std::vector<std::vector<ReconstructedParticle*> > ToolSet::CChain_Single::RC_Particle () [inline]
RC_Particle : get ReconstructedParticle in the chain， it organizes as for each particle in the MCEnd, it has a MCParticle -- vector of <ReconstructedParticles>.
Returns
std::vector<std::vector<float> > ToolSet::CChain_Single::RC_Weight () [inline]
RC_Weight : get ReconstructedParticle's weight in the chain， it organizes as for each particle in the MCEnd, it has a MCParticle -- vector of <weight>.
Returns
void ToolSet::CChain_Single::Recurse_Chain (MCParticle * input)
Recurse_Chain : get decay particles from the input.
Parameters
input
void ToolSet::CChain_Single::Set_Combined_RC ()
Set_Combined_RC : sum all ReconstructedParticle into a new particle in each chains, so that you can compare the energy/momentum loss between original MC particle and ReconstructedParticles. This will generate a new ReconstructedParticle in the heap, so remember to use Clear()
void ToolSet::CChain_Single::Set_Nav_From_MC_To_RC (LCRelationNavigator * relation)
Set_Nav_From_MC_To_RC : set Nav.
Parameters
relation
void ToolSet::CChain_Single::Set_Nav_From_RC_To_MC (LCRelationNavigator * relation)
Set_Nav_From_RC_To_MC : set Nav.
Parameters
relation
void ToolSet::CChain_Single::TraceBack_Chain (MCParticle * input)
TraceBack_Chain : get particles where the input is decayed from, it is in the opposite direction of the Recurse_Chain(). So if the input particle is in the middle position, use Recurse_Chain, will get what this input decays, using TraceBack_Chain will get where does this input coming from. combining two functions will get a complete decay chain from the hard-scattering to detector simulation.
Parameters
input
std::vector<MCParticle*> ToolSet::CChain_Single::Trim_Chain () [inline]
Trim_Chain : get trimed MC particles in the chain (from hard-scattering to final simulated particle).
Returns
The documentation for this class was generated from the following file:
CChain_Single.h